### ISSUE TITLE
Basic setup questions

### ISSUE THREAD

**Issue by YesThatAllen** [discourse/discourse-zendesk-plugin#1]
- [x] Why is the Zendesk subdomain stored separately from the rest of this plugin's setup?

<img width="782" alt="screenshot_2484" src="https://user-images.githubusercontent.com/2879972/29253217-d44eac94-803c-11e7-8287-88cbc0e8163e.png">

- [ ] When entering the right value for Zendesk URL, requesting just the subdomain may be easier.

Rather than requesting

`https://your-url.zendesk.com/api/v2`

Asking for just `your-subdomain` will prevent any issues if we have to move to v3, and especially for those using Zendesk's domain mapping.

- [x] I'm seeing a translation missing error, fwiw.
`translation missing: en.site_settings.zendesk_url`

- [x] even after setting my Zendesk URL, I still see the warning text of `Your zendesk url is not currently set`, even after a page reload.

**Comment by bekicot** [comment]
> Why is the Zendesk subdomain stored separately from the rest of this plugin's setup?
Each staff will have different zendesk credentials. But only 1 zendesk url is allowed per site. So, if the staff doesn't have privilege to change the domain, it can't change it. 

> When entering the right value for Zendesk URL, requesting just the subdomain may be easier.
That actually something I'm in doubt. But when I made the decision, one thing in mind when I give the option is, the user can have control over which version of the API. Maybe it is overkill :).  see https://github.com/zendesk/zendesk_api_client_rb/issues/340 . It is something I still consider. I also agree with your comment

> I'm seeing a translation missing error, fwiw.
definitely, will fix

> even after setting my Zendesk URL, I still see the warning text of Your zendesk URL is not currently set, even after a page reload.
Will have a look at it

**Comment by YesThatAllen** [comment]
I have rebuilt the container with today's commits and have the following updates:

It seems that the email address I had tried to enter in `/admin/plugins/zendesk-plugin` had been saved afterall. It was present after the rebuild, but did not appear earlier.

The API key had not been saved, however. Instead, the message about not having my zendesk URL stored was in the placeholder text for the API key box.

I was able to enter and save my key, however the button never changes from `Save` to `Reset` as it does for other settings in Discourse's Admin.

![image](https://user-images.githubusercontent.com/2879972/29276690-09c478c0-80d5-11e7-9ba6-1421737c0bc7.png)

**Comment by bekicot** [comment]
![image](https://user-images.githubusercontent.com/1826884/29279325-a4517520-8141-11e7-8492-6cfa02db4e98.png)
Is it enough?

**Comment by YesThatAllen** [comment]
Perfect!  The translation is working now as well.

I see your dilemma on what to store for Zendesk API url (the subdomain vs the URL).

I still think the best thing is to store the subdomain, but will leave that to you.

Thanks for these fixes.. now to test the plugin's functionality!
